name: build_html_from_rmd_files

on:
  push:
    branches:
      - "2023"

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "3.6.3"
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev
      - name: Download and install specific package versions
        run: |
          wget https://github.com/r-lib/desc/archive/refs/tags/v1.4.3.tar.gz
          wget https://github.com/r-lib/brio/archive/refs/tags/v1.1.3.tar.gz
          wget https://github.com/r-lib/downlit/archive/refs/tags/v0.4.2.tar.gz
          Rscript -e 'install.packages("desc_1.4.3.tar.gz", repos = NULL, type = "source")'
          Rscript -e 'install.packages("brio_1.1.3.tar.gz", repos = NULL, type = "source")'
          Rscript -e 'install.packages("downlit_0.4.2.tar.gz", repos = NULL, type = "source")'
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown", repos = "https://cloud.r-project.org")'
      - name: Render Book
        run: Rscript -e 'renv::restore(); bookdown::render_book("index.Rmd")'
        working-directory: ./
      - name: Add .nojekyll file
        run: touch ./_book/.nojekyll
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Github action | Rebuild book"
          git push
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book