name: build_html_from_rmd_files

on:
  push:
    branches:
      - "2023"

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "3.6.3"
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install libcurl
        run: sudo apt install -y libcurl4-openssl-dev
      - name: update and install libudunits2-dev libgdal-dev libgeos-dev libproj-dev
        run: sudo apt-get -y update && sudo apt-get install -y  libudunits2-dev libgdal-dev libgeos-dev libproj-dev
      - name: Install downlit
        run: sudo Rscript -e 'install.packages("downlit", repos = "https://cloud.r-project.org")'
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("renv"))'
      - name: Render Book
        run: Rscript -e 'renv::restore(); bookdown::render_book("index.Rmd")'
        working-directory: ./
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Github action | Rebuild book"
          git push
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
